version: '3'
services:
  telegram:
    build: ./clients/telegram
    depends_on:
      - redis
    command: ./telegram
  api:
    build: ./api
    depends_on:
      - redis
    ports:
      - 8080:8080
    command: ./api
  redis:
    image: redis:5.0.4-alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
