version: '3'
services:
  telegram:
    build: ./clients/telegram
    depends_on:
      - redis
    command: ./telegram
  api:
    build: ./api
    depends_on:
      - redis
    ports:
      - 8080:8080
    command: ./api
  redis:
    image: redis:5.0.4-alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
  admin-panel:
    container_name: admin-panel
    build: ./admin-panel
    volumes:
      - './admin-panel:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
  map-viewer:
    container_name: map-viewer
    build: ./map-viewer
    ports:
      - 3006:3000
    volumes:
      - './map-viewer:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
